import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";


const satoshi = localFont({
  src: [
    {
      path: "../assets/fonts/Satoshi-Variable.ttf",
      weight: "400 900",
    },
  ],
  variable: "--font-satoshi",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}


